name = "EventStudyInteracts"
uuid = "f9322581-1cea-4fd6-9e8e-2ae6cc4618ce"
authors = ["xq "]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Vcov = "ec2bfdc2-55df-4fc9-b9ae-4958c2cf2486"

[compat]
DataFrames = "1.5"
FixedEffectModels = "1.9.1"
Reexport = "0.1, 0.2, 1.0"
StatsAPI = "1"
StatsBase = "0.33"
StatsFuns = "0.9, 1"
StatsModels = "0.6"
Tables = "1"
Vcov = "0.6"
julia = "1.7"
